### ISSUE TITLE
Invalid Podfile

### ISSUE THREAD

**Issue by Sewb21** [nrwl/nx-labs#107]
I have a bare workflow Expo app and I keep getting an invalid Podfile error. I've deleted modules, reset caches, removed ios directory and re-ran `expo prebuild`. This app is my own source code that I have migrated but I ran into the exact same issue from a newly initialised nx-expo project.

```
Command `pod install` failed.
└─ Cause: Invalid `Podfile` file: cannot load such file -- /Users/user/Code/myapp/node_modules/expo-modules-autolinking/scripts/ios/xcode_env_generator.

 #  from /Users/sebsmith/Code/valeted/apps/business-app/ios/Podfile:1
 #  -------------------------------------------
 >  require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
 #  require File.join(File.dirname(`node --print "require.resolve('react-native/package.json')"`), "scripts/react_native_pods")
 #  -------------------------------------------
```

**Comment by Sewb21** [comment]
Fixed this by installing `expo-modules-autolinking` as it seemed to default to version 0.5.5 that didn't seem to have xcode_env_generator

**Comment by duro** [comment]
I don't think this issue should be closed. Since it remains an issue with all new projects. Some kind of fix should be implemented into the project.

I have created a reproduction repo here:

https://github.com/duro/nx-expo-repro

**Comment by duro** [comment]
BTW, I discovered that this exclusively happens when using NPM rather than Yarn as the dependency manager. With the little digging I did, where I landed was once again reaffirming that NPM is a garbage package manager, and just use Yarn.
