### ISSUE TITLE
Curious about timeline to merge expo into Nx core repo?

### ISSUE THREAD

**Issue by duro** [nrwl/nx-labs#119]
I'm curious if there is a roadmap to get the expo plug-in moved into the core Nx repo? As it stands now it often lags behind the release cycle of Nx, and it's sometimes difficult to know what Nx version it is compatible with.

At the very least it would be good to have a table in the README that tells us what version of Nx the latest stable is tested against.

**Comment by jaysoo** [comment]
Hi @duro we've added the plugin to the main repo! https://github.com/nrwl/nx/tree/master/packages/expo

Once we release it to npm we'll remove the plugin from here.

**Comment by duro** [comment]
@jaysoo Congrats. This plugin has come a long way, and you guys have really made bringing expo to Nx a reality.
