### ISSUE TITLE
The latest nx-ignore script is SLOW

### ISSUE THREAD

**Issue by mrlubos** [nrwl/nx-labs#122]
With the latest changes to `nx-ignore` 3 days ago, our builds have gone from 2-3 minutes to 8-11 minutes.

What changed? Our logs will now print this at the beginning:

```sh
Cloning github.com/org/proj (Branch: main, Commit: xxxxxxx)
--
06:10:55.844 | Cloning completed: 1.396s
06:10:55.844 | Running "npx nx-ignore app"
06:10:57.458 | npx: installed 3 in 1.525s
06:10:57.497 | ≫ Using Nx to determine if this project (app) is affected by the commit...
06:10:57.498 | nx-ignore version "14.8.9"
06:10:57.498 | cwd is "/vercel/path0"
06:10:57.499 | Installing Nx: yarn add nx@14.6.3
```

This step alone takes 5+ minutes. Previously, it would jump straight into the checks. cc @jaysoo

**Comment by burakkgunduzz** [comment]
In addition, something is broken now. All of my projects are being built right now regardless of whether they are affected or not.  
I am always seeing "Could not find Nx in the workspace, continuing the build just in case." instead of build can proceed or build is cancelled.

**Comment by mrlubos** [comment]
@burakkgunduzz not seeing the same issue, is there anything custom about your configuration? Are you also using Vercel?

**Comment by jaysoo** [comment]
Hey, there was an issue reading the Nx graph on Vercel. I had added an install step to ensure the Nx graph is built with the Nx version in the project.

It's since been patched to not require that install step.

If you continue to have any problem, please add `--verbose` flag and let me know what the output looks like.

**Comment by mrlubos** [comment]
Hey @jaysoo, thanks for the reply. I'm actually using the verbose flag, just didn't mention it in my contrived example. I can confirm this now works as expected and we're back to sub 3 minute build times. Thank you!

**Comment by burakkgunduzz** [comment]
everything is also back to normal on my side. All is good.
