### ISSUE TITLE
nx-ignore output different to nx affected output

### ISSUE THREAD

**Issue by sdjnes** [nrwl/nx-labs#125]
Not sure if this is a bug or expected behaviour.

I have a branch with 2 commits:

`HEAD~1` changes `app-1`
`HEAD` changes `app-2`

Nx affected output looks like this:
```
▶ nx affected:apps --plain --base=main
app-1 app-2
```

Whereas nx-ignore produces the following for each app
```
▶ npx nx-ignore app-1 --base=main
≫ Using Nx to determine if this project (app-1) is affected by the commit...
🛑 - Build cancelled since app-1 is not affected
```

```
▶ npx nx-ignore app-2 --base=main
≫ Using Nx to determine if this project (app-2) is affected by the commit...
✅ - Build can proceed since app-2 is affected
```

I suppose the wording around the output gives some idea ("by the commit"), but I would expect `nx affected` and `nx-ignore` to produce the same results here. 

The above commit example means that Vercel skips `app-1` but not `app-2` despite the branch having changes for both apps.

**Comment by sdjnes** [comment]
After digging into the source code, I can see that this package does essentially what I'm doing in a custom bash script for Vercel.

@jaysoo I believe the following change needs to happen on [this line](https://github.com/nrwl/nx-labs/blob/main/packages/nx-ignore/src/index.ts#L77):

```diff
await affected('print-affected', {
      type: 'app',
-    base: 'HEAD^',
+	  base: baseSha,
      head: 'HEAD',
      _: '',
});
```

I can open a PR if you agree.

**Comment by david-morris** [comment]
I've also experienced this.  In line with comparing against `HEAD^` instead of the intended base SHA, if I add a change in the newest commit which affects the project, the project will correctly be approved for build by nx-ignore.

**Comment by sdjnes** [comment]
PR has been merged and I've tested in my Vercel deployments -- everything seems to be working now.

If you don't want unnecessary builds you can write a bash script that calculates the base as either `VERCEL_GIT_PREVIOUS_SHA` or `origin/main` and also handle Vercel redeploys. See [this gist](https://gist.github.com/sdjnes/a600b68322ca163d2cea17c2ec138a20) for an idea of how it might look!

Closing this issue now.
