### ISSUE TITLE
Deno library template - change index.ts to mod.ts

### ISSUE THREAD

**Issue by Jordan-Hall** [nrwl/nx-labs#153]
I know NX standard is to use index files however, its common for a mod.ts in Deno. In Vite you tried to keep with vite standards so wondering if deno should be mod.ts?

**Comment by barbados-clemens** [comment]
thanks @Jordan-Hall, I agree we should use the mod.ts convention for Deno libs. 

I was messing publishing a deno lib as well, and that made me realize the layout for the lib could also be improved. I am thinking something similar to this

```tree
packages/sample-deno-publishable-lib
├── README.md
├── deno.json
├── mod.ts
├── project.json
└── src
    └── private api files go here
```

**Comment by Jordan-Hall** [comment]
That looks perfect to me :) I know its small change but I think it helps when moving from one to another to keep they own standards
