### ISSUE TITLE
Add deno fmt as an executor 

### ISSUE THREAD

**Issue by adume** [nrwl/nx-labs#154]
[Deno has a formatter](https://deno.land/manual@v1.30.3/tools/formatter) that can be called via `deno fmt`. It would be great if there was an executor that would call this under the hood to keep consistency with the lint and other executors currently available. 

**Edit:**
My current workaround is to add a manual `fmt` entry to my `project.json`. It looks something like this
```json
"fmt": {
  "executor": "nx:run-commands",
  "options": {
    "command": "deno fmt --config apps/my-app/deno.json"
  }
}
```

**Comment by nartc** [comment]
Hi @adume, thank you for opening the issue. We initially thought about adding the `fmt` target but we felt like it's not worth it, especially when you're in an Nx workspace with Prettier and Deno Formatter combined. In addition, `nx format` uses `prettier` and will use Prettier configuration to format the whole workspace whereas `deno fmt` runs using its own configuration unless you match the prettier config with deno config.

At the moment, prettier can format Deno files well enough (as they are just TypeScript). If `deno fmt` is something you want to use for your project, then the workaround using `run-commands` would be sufficient enough. You can also use the short-hand syntax

```json
"fmt": {
  "command": "deno fmt --config apps/my-app/deno.json"
}
```
