### ISSUE TITLE
Web

### ISSUE THREAD

**Issue by tomnoir** [nrwl/nx-labs#16]
Whilst building for web (start or build app), no @workspace/[xxx] imports are found.

**Comment by juristr** [comment]
can you please provide some more details what you've been trying to do? like which serious
setup, which version, ideally a reproduction repository etc

**Comment by mailaneel** [comment]
+1 for not able to resolve paths for libs when using the web, no problem when using native(ios)

Error: Unable to resolve/Module not found @scope/lib when used from App.tsx

Also seeing these errors with web `nx web APP_NAME`

```
./node_modules/react-native-gesture-handler/lib/module/index.js:73
"export 'ComposedGestureType' (reexported as 'ComposedGesture') was not found in './handlers/gestures/gestureComposition'
  71 | export { NativeGestureType as NativeGesture } from './handlers/gestures/nativeGesture';
  72 | export { ManualGestureType as ManualGesture } from './handlers/gestures/manualGesture';
> 73 | export {
  74 |   ComposedGestureType as ComposedGesture,
  75 |   RaceGestureType as RaceGesture,
  76 |   SimultaneousGestureType as SimultaneousGesture,
./node_modules/react-native-gesture-handler/lib/module/index.js:73
"export 'ExclusiveGestureType' (reexported as 'ExclusiveGesture') was not found in './handlers/gestures/gestureComposition'
  71 | export { NativeGestureType as NativeGesture } from './handlers/gestures/nativeGesture';
  72 | export { ManualGestureType as ManualGesture } from './handlers/gestures/manualGesture';
> 73 | export {
  74 |   ComposedGestureType as ComposedGesture,
  75 |   RaceGestureType as RaceGesture,
  76 |   SimultaneousGestureType as SimultaneousGesture,
./node_modules/react-native-gesture-handler/lib/module/index.js:66
```

**Comment by xiongemi** [comment]
> 

I think you might need to create a custom webpack.config.js file under your app. you might also need to install `tsconfig-paths-webpack-plugin`. it should find the path of the lib imports:

```
const createExpoWebpackConfigAsync = require('@expo/webpack-config');
const { TsconfigPathsPlugin } = require('tsconfig-paths-webpack-plugin');

module.exports = async function (env, argv) {
  const config = await createExpoWebpackConfigAsync(env, argv);

  const rules = config.module.rules[1]?.oneOf;
  if (rules) {
    rules.push({
      test: /\.(mjs|[jt]sx?)$/,
      exclude: /node_modules[/\\](?!react-native-vector-icons)/,
      use: {
        loader: require.resolve('@nrwl/web/src/utils/web-babel-loader.js'),
        options: {
          presets: [
            [
              '@nrwl/react/babel',
              {
                runtime: 'automatic',
              },
            ],
          ],
        },
      },
    });
  }

  const extensions = ['.ts', '.tsx', '.mjs', '.js', '.jsx'];
  let tsConfigPath = 'tsconfig.json';

  config.resolve.plugins.push(
    new TsconfigPathsPlugin({
      configFile: tsConfigPath,
      extensions,
    })
  );
  return config;
};

```

**Comment by xiongemi** [comment]
> +1 for not able to resolve paths for libs when using the web, no problem when using native(ios)
> 
> Error: Unable to resolve/Module not found @scope/lib when used from App.tsx
> 
> Also seeing these errors with web `nx web APP_NAME`
> 
> ```
> ./node_modules/react-native-gesture-handler/lib/module/index.js:73
> "export 'ComposedGestureType' (reexported as 'ComposedGesture') was not found in './handlers/gestures/gestureComposition'
>   71 | export { NativeGestureType as NativeGesture } from './handlers/gestures/nativeGesture';
>   72 | export { ManualGestureType as ManualGesture } from './handlers/gestures/manualGesture';
> > 73 | export {
>   74 |   ComposedGestureType as ComposedGesture,
>   75 |   RaceGestureType as RaceGesture,
>   76 |   SimultaneousGestureType as SimultaneousGesture,
> ./node_modules/react-native-gesture-handler/lib/module/index.js:73
> "export 'ExclusiveGestureType' (reexported as 'ExclusiveGesture') was not found in './handlers/gestures/gestureComposition'
>   71 | export { NativeGestureType as NativeGesture } from './handlers/gestures/nativeGesture';
>   72 | export { ManualGestureType as ManualGesture } from './handlers/gestures/manualGesture';
> > 73 | export {
>   74 |   ComposedGestureType as ComposedGesture,
>   75 |   RaceGestureType as RaceGesture,
>   76 |   SimultaneousGestureType as SimultaneousGesture,
> ./node_modules/react-native-gesture-handler/lib/module/index.js:66
> ```

you might need to remove the `import 'react-native-gesture-handler';` in index.js to make the web work. however, if you need it in the mobile app, you might still need this import.

**Comment by xiongemi** [comment]
i got the web working using the custom webpace config: https://github.com/xiongemi/nx-expo-poetry/blob/main/apps/poetry-app/webpack.config.js

This is what i got by running `nx build-web`:
https://xiongemi.github.io/nx-expo-poetry/

this is my github repo with expo: https://github.com/xiongemi/nx-expo-poetry
