### ISSUE TITLE
@nrwl/deno will break in CI

### ISSUE THREAD

**Issue by zizifn** [nrwl/nx-labs#163]
Below is the GitHub action output for `npm install`

```
npm ERR! command failed
npm ERR! command sh -c node ./bin/compute-project-graph
npm ERR! >  NX   Daemon Server - Stopped
npm ERR! node:events:491
npm ERR!       throw er; // Unhandled 'error' event
npm ERR!       ^
npm ERR! 
npm ERR! Error: spawn deno ENOENT
npm ERR!     at ChildProcess._handle.onexit (node:internal/child_process:283:19)
npm ERR!     at onErrorNT (node:internal/child_process:476:16)
npm ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
npm ERR! Emitted 'error' event on ChildProcess instance at:
npm ERR!     at ChildProcess._handle.onexit (node:internal/child_process:289:12)
npm ERR!     at onErrorNT (node:internal/child_process:476:16)
npm ERR!     at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
npm ERR!   errno: -2,
npm ERR!   code: 'ENOENT',
npm ERR!   syscall: 'spawn deno',
npm ERR!   path: 'deno',
npm ERR!   spawnargs: [
npm ERR!     'info',
npm ERR!     '--import-map=import_map.json',
npm ERR!     '--json',
npm ERR!     '--unstable',
npm ERR!     '--no-config',
npm ERR!     'apps/deno-vless/deno.json'
npm ERR!   ]
npm ERR! }
npm ERR! 
npm ERR! Node.js v18.[14]
```

**Comment by barbados-clemens** [comment]
Do you have deno installed in the CI agent?

You'll need to have it installed before running npm install since the nx post install hook is going to create the project graph, and deno is needed to build the project graph. 

The error message should be better once #166 is released

**Comment by zizifn** [comment]
> Do you have deno installed in the CI agent?
> 
> You'll need to have it installed before running npm install since the nx post install hook is going to create the project graph, and deno is needed to build the project graph.
> 
> The error message should be better once #166 is released

is there are any way to make deno install in node module? I can't controll some CI when use deoloy method like create project in vercel dashboard.

**Comment by barbados-clemens** [comment]
deno is not a node_module. it's like a runtime like node is. 
you'll need to find away to install it in CI. 
https://deno.land/manual@v1.31.3/getting_started/installation

looks you can customize the image on vercel 
https://vercel.com/docs/concepts/deployments/build-image

also if you remove the @nrwl/deno entry in the plugins entry in the nx.json that will stop from trying to run the deno graph extension.
