### ISSUE TITLE
Can't get expo to launch at all

### ISSUE THREAD

**Issue by seanaguinaga** [nrwl/nx-labs#21]
Does not launch on my machine in iOS Emulator at all

No files changed from using default nx plugin generator

Stays stuck on splash screen, no errors

**Comment by xiongemi** [comment]
i just tried locally, and it works fine for me.

do you get this error?
```
Error: Please define "ios.bundleIdentifier" in app.json.
```

in your app's app.json, you have to add the bundleIdentifier:
```
"ios": {
      "bundleIdentifier": "<your bundle indentifier>"
    },
```

i create the workspace with `npx create-nx-workspace@latest <workspace-name>`
then i go into the workspace folder and install @nrwl/expo using `npm install @nrwl/expo`
then i generate an expo app using `nx generate @nrwl/expo:app <app-name>`
after that I run `nx start <app-name>` and it works fine on the ios simulator.

**Comment by mantas7776** [comment]
I am having the same issue as well. Web version works, ios does not. If i create expo project with `npx create-expo-app` it works, with nx it does not. @xiongemi
