### ISSUE TITLE
Add webpack's generatePackageJson option to rspack's project configuration

### ISSUE THREAD

**Issue by dgmachado** [nrwl/nx-labs#226]
### What problem does this feature solve?

The generatePackageJson option can be configured in project.json file and consumed by the Webpack.  It's desirable that this option is supported by Rspack.

**generatePackageJson**
Generates a package.json and pruned lock file with the project's node_module dependencies populated for installing in a container. If a package.json exists in the project's directory, it will be reused with dependencies populated.

### What does the proposed API of configuration look like?

```json
         "options": {
              ...,
              "maxWorkers": 1,
              "memoryLimit": 2048,
              "generatePackageJson": false,
              ...,
         }
```

**Comment by kodeine** [comment]
@mandarini is there any update on this? the feature does exist in [rspack](https://github.com/web-infra-dev/rspack/blob/main/examples/plugin-compat/rspack.config.js#L8) though.

**Comment by mandarini** [comment]
Hi there @kodeine ! It is not in our plans at the moment. If anyone from the community wants to give this a short, I can help by providing feedback!
