### ISSUE TITLE
What's the proper way to update @rspack/core ?

### ISSUE THREAD

**Issue by yuqianma** [nrwl/nx-labs#233]
Newbie to Nx and Rspack. The one line command `pnpm create nx-workspace myrspackapp --preset=@nrwl/rspack  --pm=pnpm` is awesome! Thanks for the work.

But I'm struggling with updating the repo which I created weeks ago.
I thought `nx migrate latest` would get things done but not.
Then I tried `nx migrate @nrwl/rspack`. It updated the `@nrwl/rspack` package but none of `@repack/*`.

I wonder what is the best way to update `@rspack/*`. (Or what does the Nx docs mean by saying "Automate Updating Dependencies"?)

**Comment by jaysoo** [comment]
You can install it manually (`npm i @rspack/core@latest` or bump it in your `package.json` file). We specify `~0.1.0`, which means anything below `0.2.0` should be supported.

A migration will be coming soon for `@nx/rspack` once we publish that new scope.
