### ISSUE TITLE
Usage of react native debugger

### ISSUE THREAD

**Issue by ratoi-crysty** [nrwl/nx-labs#24]
Currently, React Native Debugger is unable to detect the application when it's running with @nrwl/expo, while working fine when I run a test project using expo cli.

Is there something that I'm missing?

I tested with both ports: 19000 and 19001.
Tested on Linux Mint.

**Comment by ratoi-crysty** [comment]
Closing this issue as the port is configured in `project.json` which has a default `8081`.

**Comment by itorres-1** [comment]
Could you help a someone new to nx and working on a react native / expo app how to setup debugging? For content, I've also got an api running with `npx nx serve api` that already auto attacked when it runs.

**Comment by ratoi-crysty** [comment]
@itorres-1 just to understand your issue. 
The mobile application is running, you can use the default browser debug, but you could not debug on React Native Debugger?
As that was my issue.
