### ISSUE TITLE
ReadMe typo - `nx start myapp` -- change -> `nx serve myapp` | `yarn start myapp`

### ISSUE THREAD

**Issue by un33k** [nrwl/nx-labs#29]
There is a tiny typo in the readme file.

We may want to change:

`nx start myapp` to either `nx serve myapp` or `yarn start myapp`

https://github.com/nrwl/nx-labs/tree/main/packages/expo

**Comment by xiongemi** [comment]
i think for expo, start command is a valid, serve is just a through of start command

nx start myapp
nx serve myapp

should be the same thing.
