### ISSUE TITLE
Can't resolve nx libraries

### ISSUE THREAD

**Issue by fjckls** [nrwl/nx-labs#32]
I add a new nx library like so `nx generate @nrwl/workspace:library utils`, then when I try to import it `import {sleep} from "@nx-workspace/utils";`, I get an error `Module not found: Can't resolve '@nx-workspace/utils'`.

I'm able to import the same library in other apps, but not the expo. What could be the problem here? It seems that the project generated by expo can't resolve the path....

**Comment by xiongemi** [comment]
i tried the above command and it seems fine for the latest expo version. i am able to run `nx start` and launch the app in the simulator. could you upgrade and try again?
