### ISSUE TITLE
@nx/remix | setup-tailwind | works fine in dev mode but not after build 

### ISSUE THREAD

**Issue by Mat-moran** [nrwl/nx-labs#330]
Hi, 

I was testing out the new functionalities of the latest version of and I think Tailwind configuration is not working properly.

It is working in during development but when you build and start the app you get the next warning message and you loose styles.

```
warn - The `content` option in your Tailwind CSS configuration is missing or empty.
warn - Configure your content sources or your generated CSS will be missing styles.
```

This warning does not appear in development mode.

I updated to the newest Remix version and its does not work neither.

## Steps to reproduce
- create a remix app `nx g @nx/remix:app myapp`
- execute the tailwind setup`nx g @nx/remix:setup-tailwind myapp`
- Add a red background in the index file ` <h1 className="bg-red-600">Welcome to Remix Monorepo</h1>`

You can see it in development mode but when you build your app the red backgroud is lost.

**Comment by itxch** [comment]
I had similar issues when using the new remix build - what happens if you run the build command from within the apps/myapp dir?

My setup is slightly different (using Tailwind via postcss) and I had to do something like this



```js
// tailwind.config.js

// Sets the absolute path to directories
const generateContentPaths = paths => paths.map(path => join(__dirname, path));

/** @type {import('tailwindcss').Config} */
module.exports = {
  content: generateContentPaths(["./app/**/*.{ts,tsx,jsx,js}"]),
  theme:  {},
  plugins: [],
};
```

```js
// postcss.config.js

const path = require("path");
module.exports = {
  plugins: {
    tailwindcss: path.join(__dirname, "tailwind.config.js"),
    autoprefixer: {},
    ...(process.env.NODE_ENV === "production" ? { cssnano: {} } : {}),
  },
};

```

**Comment by Mat-moran** [comment]
Hi @itxch , if I do it from the app folder it works fine.

Have you got any idea why it is happening?

**Comment by itxch** [comment]
> Hi @itxch , if I do it from the app folder it works fine.
> 
> 
> 
> Have you got any idea why it is happening?

I think it's to do with how the files are referenced in tailwind's content option. If you updated the path to be something like apps/myapp/app/ etc rather thank ./app it might solve it?

**Comment by Mat-moran** [comment]
This PR https://github.com/nrwl/nx-labs/pull/332 close this issue

Thanks for the help
