### ISSUE TITLE
Upgrading nx/remix to run remix 2.1.0

### ISSUE THREAD

**Issue by 127** [nrwl/nx-labs#343]
What about upgrading @nx/remix to support 2.1.0 (2.2.0)? Any plans?

**Comment by 127** [comment]
2.2.0 support vite since yesterday
https://github.com/remix-run/remix/releases/tag/remix%402.2.0

**Comment by travtarr** [comment]
Hopefully this can open up Remix to be an official plugin since I believe the only thing holding it back before was a way to get access to the compiler (which Remix's Vite plugin should allow) for a more seamless integration with Nx.

I imagine this will be fairly straightforward as it will allow us to just re-use the `@nx/vite` package's executors.

**Comment by underfisk** [comment]
I'm also looking forward having remix v2 support with vite (as an opt in)

**Comment by Mat-moran** [comment]
Me too, I am also waiting for this to be came up! 😄 It is incredible the development experience with the new Vite support
you can check it here https://www.youtube.com/watch?v=B_vIp4xETl4 and how to migrate an actual remix app here
https://www.youtube.com/watch?v=g60FI9Oyfs4

**Comment by Mat-moran** [comment]
remix v2 is comming ❄️  https://github.com/nrwl/nx-labs/pull/350

**Comment by johannesschobel** [comment]
I think this issue can be closed @127

**Comment by kosiakMD** [comment]
@johannesschobel why it's closed? what is the solution for nx + remix v2+?

**Comment by johannesschobel** [comment]
@kosiakMD : i think the latest version of `@nx/remix` uses `remix v.2.x` under the hood. You may need to check the `package.json` file in your mono-repository.

All the best

**Comment by nadiTime** [comment]
Trying to update remix in nx to use vite but getting this error when running dev server
<img width="673" alt="image" src="https://github.com/nrwl/nx-labs/assets/10961775/7ac7c24d-30a9-4009-ad5c-0d67d1588657">

when im removing the nx/vite pluging from nx.json it works, 
any ideas how to solve this without removing the plugin?

**Comment by binaryartifex** [comment]
latest nx remix generator isn't using vite and im getting the same errors as @nadiTime when i try to manually include it
