### ISSUE TITLE
[expo] can't use nx libs into expo app

### ISSUE THREAD

**Issue by makhataibar** [nrwl/nx-labs#36]
I'm try import from /libs (generated by expo and react) and catch error:
<img width="556" alt="Снимок экрана 2022-04-13 в 12 30 15" src="https://user-images.githubusercontent.com/27006656/163114157-c2bc78bf-edbc-4338-8de9-1fba102f5f1d.png">
<img width="556" alt="Снимок экрана 2022-04-13 в 12 29 34" src="https://user-images.githubusercontent.com/27006656/163114178-afaa8c4a-0c1e-41f7-a7fb-12e8ab134220.png">

**Comment by xiongemi** [comment]
i think you in your webpack.config.js, add the line:
```
config.resolve.symlinks = true;
```

**Comment by makhataibar** [comment]
@xiongemi thanks, that's work for me)

it's a bug?

**Comment by xiongemi** [comment]
i fixed it for pr https://github.com/nrwl/nx-labs/pull/44/files

after migrate to latest @nrwl/exp (14.0.1), now for the webpack.config.js, you can change it to:
const createExpoWebpackConfigAsync = require('@expo/webpack-config');
const { withNxWebpack } = require('@nrwl/expo');

module.exports = async function (env, argv) {
  let config = await createExpoWebpackConfigAsync(env, argv);
  config = await withNxWebpack(config);

  // You can override the config here, for example:
  // config.resolve.alias = {
  //   ...config.resolve.alias,
  //   react: path.resolve('../../node_modules/react'),
  // };
   
  return config;
};
