### ISSUE TITLE
nx-ignore does not support nx@19.x

### ISSUE THREAD

**Issue by mcalhoun** [nrwl/nx-labs#401]
This package does not support nx version 19 and above because the [nx commands](https://github.com/nrwl/nx-labs/blob/main/packages/nx-ignore/src/index.ts#L109)  run under the hood are no longer supported in nx.

For example:

 Use `nx graph --affected`, or `nx affected --graph` instead depending on which best suits your use case. The `affected:graph` command has been removed in Nx 19.

**Comment by ucheol2** [comment]
```
nx show projects --projects=... --affected
```
this command can help

**Comment by mcalhoun** [comment]
>nx show projects --projects=... --affected
> this command also can help

I think you're misunderstanding the issue I'm reporting. The command that is run is hard coded in the [nx-ignore](https://github.com/nrwl/nx-labs/blob/main/packages/nx-ignore/src/index.ts#L109) package, making this package incompatible with nx v19+

**Comment by ucheol2** [comment]
you are right. I also know it.
I just give another command option to maintainer rather than `nx graph --affected` or `nx affected --graph`

**Comment by jaysoo** [comment]
Fixed here https://github.com/nrwl/nx-labs/pull/403

**Comment by jaysoo** [comment]
Needs this PR as well https://github.com/apps/nx-cloud

**Comment by mcalhoun** [comment]
@jaysoo Thanks, it's working now. I appreciate the quick fix on this!
