### ISSUE TITLE
The latest version of create-nx-workspace doesn't support @nrwl/remix presets

### ISSUE THREAD

**Issue by NachoVazquez** [nrwl/nx-labs#41]
## The Problem

When attempting to create a new Nx workspace using a Remix preset using the command

```bash
npx create-nx-workspace@latest --preset=@nrwl/remix
```

 we get the following error

```bash
Invalid values:
  Argument: preset, Given: "@nrwl/remix", Choices: "apps", "empty", "core", "npm", "ts", "web-components", "angular", "angular-nest", "react", "react-express", "react-native", "next", "nest", "express"
```

To make it work I had to use version 13.7.1 like this

```bash
npx create-nx-workspace@13.7.1 --preset=@nrwl/remix
```

## Expected Behavior

The latest `create-nx-workspace` should support the Remix preset

## Additional Info

OS: MacOS 12.3.1 
CPU: Chip M1 Pro
Node: 16.14.2

**Comment by philipjfulcher** [comment]
I think this issue was resolved by [this issue on the main reop](https://github.com/nrwl/nx/issues/9858). I'll confirm later.

**Comment by philipjfulcher** [comment]
Confirmed, closed by [this issue](https://github.com/nrwl/nx/issues/9858)
