### ISSUE TITLE
Remix app not able to resolve library

### ISSUE THREAD

**Issue by NachoVazquez** [nrwl/nx-labs#43]
## The Problem

Importing a `@nrwl/remix` library from a `@nrwl/remix` application fails during the build phase with an error

```bash
✘ [ERROR] Could not resolve "@remix-with-nx/mylib"

    app/root.tsx:13:22:
      13 │ import { Mylib } from '@remix-with-nx/mylib';
         ╵                       ~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@remix-with-nx/mylib" as external to exclude it from the bundle, which will remove this error.
```

## Steps to reproduce

1. Create nx workspace running

```bash
npx create-nx-workspace@13.7.1 --preset=@nrwl/remix
```

2. Create Remix library

```bash
npx nx g @nrwl/remix:lib mylib
```

3. Build the Remix library

```bash
npx nx build mylib
```

4. Declare the library as a dependency in the Remix application `package.json`

```json
{
  "private": true,
  "name": "webapp",
  "description": "",
  "license": "",
  "scripts": {
    "build": "npx remix build",
    "dev": "npx remix dev",
    "postinstall": "npx remix setup node",
    "start": "npx remix-serve build"
  },
  "dependencies": {
    "@remix-run/react": "^1.0.6",
    "react": "^17.0.2",
    "react-dom": "^17.0.2",
    "remix": "^1.0.6",
    "@remix-run/serve": "^1.0.6",
    "@remix-with-nx/mylib": "libs/mylib/dist"
  },
  "devDependencies": {
    "@remix-run/dev": "^1.0.6",
    "@types/react": "^17.0.24",
    "@types/react-dom": "^17.0.9",
    "typescript": "^4.1.2"
  },
  "engines": {
    "node": ">=14"
  },
  "sideEffects": false
}
```

5. Import the library on the `root.tsx` component.

```ts
import { Mylib } from '@remix-with-nx/mylib';
```

6. Build the application 

```bash
npx nx build webapp
```

## Expected Behavior

Remix applications should allow importing libraries as shown in the [tutorial video](https://youtu.be/yUuEA4V6DJ0?t=94)

## Addtional Info

OS: MacOS 12.3.1
CPU: Chip M1 Pro
Node: 16.14.2

**Comment by ggaulard** [comment]
Is there any progress on this issue ?

For what I understand we may need to indicate to esbuild the lib as external but I don't see where to define this.

**Comment by gnuechtel** [comment]
@NachoVazquez I tried your steps and it still does not work with Nx 14.6.4.

But if you add the library to `tsconfig.base.json` in the root folder it works:

```
"paths": {
  "~/*": ["./app/*"],
  "@remix-with-nx/mylib": ["../../libs/mylib/dist"]
}
```

Though, the remix plugin should add this, but never mind, it's still in the lab.
Hopefully, they we will put more energy on this plugin, because Nx and Remix could have a great relationship if they are not too relaxed about each other ;-)

**Comment by NachoVazquez** [comment]
Thanks for the info @gnuechtel !!

**Comment by gnuechtel** [comment]
Con mucho gusto! I tried it today and was so excited when it worked! And it's even greater, when I can share this!

**Comment by gnuechtel** [comment]
@philipjfulcher So it should be just a line of code to be added to the generator?

**Comment by juristr** [comment]
@gnuechtel I just linked an open PR which should fix this issue. The path rewrite inside the remix generated TS config files is kinda problematic in general as it is generated by Remix from the point of view of it being the only app/lib.

In an Nx workspace, given how Nx manages dependencies via TS path mappings, you'd probably not want to have the `"~/*": ["./app/*"]` mapping, but just resolve in a "relative-path" fashion within the Remix app, while you have the libs properly mapped at the workspace-root level `tsconfig.base.json`.
