### ISSUE TITLE
Expo React 18 support?

### ISSUE THREAD

**Issue by Deekor** [nrwl/nx-labs#55]
Seems nx expo depends on an old version of expo that doesnt support react 18:

`React version 18.1.0 is incompatible with Expo version 44.0.6. Nx will downgrade the version to 17.0.1.`

**Comment by niyowski** [comment]
@Deekor React Native doesn't support React 18 just yet. See [here](https://reactnative.dev/blog/2022/03/30/version-068).

> React 18's new rendering engine is not supported by React Native 0.68, this will happen in a future version. This is because React 18 relies on the New Architecture to benefit from the new capabilities presented in [the React 18 announcement blog post](https://reactjs.org/blog/2022/03/29/react-v18.html). For more information, see the [React Conf keynote here](https://www.youtube.com/watch?v=FZ0cG47msEk&t=1530s).

**Comment by Deekor** [comment]
> @Deekor React Native doesn't support React 18 just yet. See [here](https://reactnative.dev/blog/2022/03/30/version-068).
> 
> > React 18's new rendering engine is not supported by React Native 0.68, this will happen in a future version. This is because React 18 relies on the New Architecture to benefit from the new capabilities presented in [the React 18 announcement blog post](https://reactjs.org/blog/2022/03/29/react-v18.html). For more information, see the [React Conf keynote here](https://www.youtube.com/watch?v=FZ0cG47msEk&t=1530s).

Good catch. I still think expo should be update to 45 though.

**Comment by xiongemi** [comment]
once expo upgrade to latest react-native, this issue should be resolved.

**Comment by xiongemi** [comment]
it should be fixed with @nrwl/expo version 14.1.1. you can update by running `nx migrate @nrwl/expo`.
