### ISSUE TITLE
Use EAS for 'nx build-<platform>'

### ISSUE THREAD

**Issue by bombillazo** [nrwl/nx-labs#67]
Currently the `nx build-ios` and `nx build-android` commands are utilizing the expo-cli commands `expo build:ios` and `expo build:android` to build apps. These are deprecated and will be phased out in favor of using the EAS cli:

```sh
expo build:ios has been superseded by eas build. Learn more: https://blog.expo.dev/turtle-goes-out-to-sea-d334db2a6b60
expo build:ios will be discontinued on January 4, 2023.
```

It would be great to support EAS for builds as it is the new standard for Expo applications.

**Comment by xiongemi** [comment]
to do eas build, simply go to your app folder `cd apps/<your app>` and run `eas build`.

**Comment by bombillazo** [comment]
Hey! Thanks for responding, that's precisely what I have now as a custom script, but would be nice to have it default part of nx expo.

**Comment by xiongemi** [comment]
this is a feature request to have command for eas build.

**Comment by xiongemi** [comment]
this feature is added https://github.com/nrwl/nx-labs/pull/84. now you can run `nx build <your app>` to trigger eas build.
