### ISSUE TITLE
Unable to resolve modules with path starting with ./

### ISSUE THREAD

**Issue by willykurmann** [nrwl/nx-labs#68]
Hi all,

When building expo app for ios/android with the following command:
```
eas build --platform all --non-interactive --auto-submit --clear-cache --no-wait
```

I get the following error:

![image](https://user-images.githubusercontent.com/496549/172619670-eea67a2e-c500-475c-8e92-ba001cf9f102.png)

Obviously,  this component exists at the correct location:
![image](https://user-images.githubusercontent.com/496549/172620000-79a757f9-f319-4725-afc3-f70bf54ffde2.png)
![image](https://user-images.githubusercontent.com/496549/172620106-fd23c56b-afe5-4ab5-b29c-482fe8c44bd0.png)
![image](https://user-images.githubusercontent.com/496549/172620245-fc35ce36-6265-4768-a07a-c1910a0fadc8.png)

There's no error for ```ErrorFallbackScreen```which is imported the same way.

### env
eas-cli/0.53.1 darwin-x64 node-v16.15.0
expo 44.0.6
nx 13.10.3

``tsconfig.json``and ``tsconfig.app.json`` files are the one created by the ``generate``command.

Would you have any idea how to solve this ?

Thanks !

**Comment by willykurmann** [comment]
@xiongemi,  could you please help me solve this issue ? (sorry for tagging 😉, but your help was precious and most appreciated last time )

**Comment by xiongemi** [comment]
const { getDefaultConfig } = require('@expo/metro-config');
const { withNxMetro } = require('@nrwl/expo');

const defaultConfig = getDefaultConfig(__dirname);

module.exports = (async () => {
  defaultConfig.transformer.babelTransformerPath = require.resolve(
    'react-native-svg-transformer'
  );
  defaultConfig.resolver.assetExts = defaultConfig.resolver.assetExts.filter(
    (ext) => ext !== 'svg'
  );
  defaultConfig.resolver.sourceExts.push('svg');
  return withNxMetro(defaultConfig, {
    // Change this to true to see debugging info.
    // Useful if you have issues resolving modules
    debug: false,
    // all the file extensions used for imports other than 'ts', 'tsx', 'js', 'jsx'
    extensions: [],
    projectRoot: __dirname,
    watchFolders: []
  });
})();

**Comment by willykurmann** [comment]
Hi @xiongemi,

so I installed latest version of nrwl/expo and also migrated to SDK 45 but still doesn't work.

When using ``expo start``,  app is working as expected.

any idea ?

**Comment by xiongemi** [comment]
the error is about @nrwlworkspace. what version of @nrwl/workspace are you using? if @nrwl/workspace the latest version? if not, could you run `nx migrate latest`?

**Comment by atmeshwar-classic** [comment]
Hi @xiongemi,

I use the following versions of the nx packages.
![image](https://user-images.githubusercontent.com/62533739/173354755-d5e52fb5-f923-4413-a32c-7552f7db913e.png)

On a blank project the build ran fine. But after copying the src folder, we ran into the above issue.

**Comment by willykurmann** [comment]
> @xiongemi same project,  working together 😉

**Comment by willykurmann** [comment]
I just discover something weird

Everything indicate that the file exists:
![image](https://user-images.githubusercontent.com/496549/173521096-83cdd215-7ffd-4526-ae0d-b62579d47f7b.png)
![image](https://user-images.githubusercontent.com/496549/173521193-4076e4c9-0418-4319-ba3c-eb26ffbd7e49.png)
![image](https://user-images.githubusercontent.com/496549/173521255-161e4dce-c22d-4847-89fc-76cd09baabe3.png)
![image](https://user-images.githubusercontent.com/496549/173522145-f1ce20c1-2201-46bf-975a-c8dd274c824e.png)


Seems file exist, but in expo I got this:
![image](https://user-images.githubusercontent.com/496549/173521722-85ce7dbc-982c-4d83-bf2e-28dce991a790.png)

**Comment by willykurmann** [comment]
@xiongemi  we found the issue !

Someone added in gitignore ``*bar``( copy/paste from a template I guess).
and thus our ``NotificationBar``compoenent was ignored from git and also from eas build archive.
This doc was very helpful,  as we could inspect the archive and assert that files were already missing at this point.
https://github.com/expo/fyi/blob/main/eas-build-archive.md

Anyway,  thanks for your support !

**Comment by xiongemi** [comment]
lol. no problem. good to hear that problem is resolved.
