### ISSUE TITLE
Metro bundler cannot resolve fonts import  

### ISSUE THREAD

**Issue by NikolaiChirkov** [nrwl/nx-labs#75]
I decided to migrate from bunch of little repositories to one mono-repository. 

And here comes the problem: in monorepo metro bundler resolves paths from expo-font in a strange way: it concats absolute path & server address. I wasn't meet that problem when projects were in separated repos

Here is example of strange path created by metro resolver:

![image](https://user-images.githubusercontent.com/64710291/173701799-2b07f96c-4d9e-4202-9bf9-13f8703ea0c0.png)

Also intresting detail: that problem appears in only when app already fully loaded on device, not while bundling

All configs was created by @nrwl/expo, nothing is changed in them

I already tried to change metro.config, but meet a problem with the resolveRequest, which was null. Funny part is that, resolveRequest was described as a function at metro docs & interfaces

Here's how i import fonts:  

![image](https://user-images.githubusercontent.com/64710291/173702505-17945dc7-5631-49ec-b60e-b76892146129.png)

Here's where fontConfig come to expo-font hook:

![image](https://user-images.githubusercontent.com/64710291/173702596-98de333f-fcd6-4465-ad61-77252b36c298.png)

May you help me, please?

I can provide additional info, if u need it. I just don't know what can be useful

**Comment by NikolaiChirkov** [comment]
> is fonts the only thing not loaded? are you using `expo-font`? if `expo-font` added to app's package.json? like `"expo-font": "*"`?

Fonts loaded with expo-font, expo-font added to package.json, only fonts couldn't be loaded

**Comment by xiongemi** [comment]
i tried with expo-font on my nx expo example project: https://github.com/xiongemi/nx-expo-poetry/pull/2/files. it works for me out of the box. I did not run into any metro issues.
it works for me for both ios and android simulators.

do you have the correct relative path to your font files?

![Simulator Screen Shot - iPhone 13 - 2022-06-17 at 14 25 23](https://user-images.githubusercontent.com/16211801/174357680-b90492e6-83fe-48d0-a4f7-3c229258bdbd.png)

**Comment by NikolaiChirkov** [comment]
> i tried with expo-font on my nx expo example project: https://github.com/xiongemi/nx-expo-poetry/pull/2/files. it works for me out of the box. I did not run into any metro issues. it works for me for both ios and android simulators.
> 
> do you have the correct relative path to your font files?
> 
> ![Simulator Screen Shot - iPhone 13 - 2022-06-17 at 14 25 23](https://user-images.githubusercontent.com/16211801/174357680-b90492e6-83fe-48d0-a4f7-3c229258bdbd.png)

**Comment by xiongemi** [comment]
@NikolaiChirkov  what version of @nrwl/expo are you using? also what does your metro.config.js look like. mine looks like this:
```
const { getDefaultConfig } = require('@expo/metro-config');
const { withNxMetro } = require('@nrwl/expo');

const defaultConfig = getDefaultConfig(__dirname);

module.exports = (async () => {
  defaultConfig.transformer.babelTransformerPath = require.resolve(
    'react-native-svg-transformer'
  );
  defaultConfig.resolver.assetExts = defaultConfig.resolver.assetExts.filter(
    (ext) => ext !== 'svg'
  );
  defaultConfig.resolver.sourceExts.push('svg');
  return withNxMetro(defaultConfig, {
    // Change this to true to see debugging info.
    // Useful if you have issues resolving modules
    debug: false,
    // all the file extensions used for imports other than 'ts', 'tsx', 'js', 'jsx'
    extensions: [],
    projectRoot: __dirname,
    watchFolders: []
  });
})();

```
do you have an example repo?

**Comment by NikolaiChirkov** [comment]
> @NikolaiChirkov what version of @nrwl/expo are you using? also what does your metro.config.js look like. mine looks like this:
> 
> ```
> const { getDefaultConfig } = require('@expo/metro-config');
> const { withNxMetro } = require('@nrwl/expo');
> 
> const defaultConfig = getDefaultConfig(__dirname);
> 
> module.exports = (async () => {
>   defaultConfig.transformer.babelTransformerPath = require.resolve(
>     'react-native-svg-transformer'
>   );
>   defaultConfig.resolver.assetExts = defaultConfig.resolver.assetExts.filter(
>     (ext) => ext !== 'svg'
>   );
>   defaultConfig.resolver.sourceExts.push('svg');
>   return withNxMetro(defaultConfig, {
>     // Change this to true to see debugging info.
>     // Useful if you have issues resolving modules
>     debug: false,
>     // all the file extensions used for imports other than 'ts', 'tsx', 'js', 'jsx'
>     extensions: [],
>     projectRoot: __dirname,
>     watchFolders: []
>   });
> })();
> ```
> 
> do you have an example repo?

Version of Expo 14.3.0, exactly same metro.config (all configs was created by default & not changed, only exception - eslint config)

**Comment by NikolaiChirkov** [comment]
Link to the example app repo: https://github.com/NikolaiChirkov/nx-expo-example

**Comment by NikolaiChirkov** [comment]
Damn, seems like I solved problem

**Comment by NikolaiChirkov** [comment]
@xiongemi Thanks for help, if your repo's package.json helps a lot
