### ISSUE TITLE
devDependencies `@types/react` version 17.0.2 not existed, but have no way to update in the workspace 

### ISSUE THREAD

**Issue by kenchoong** [nrwl/nx-labs#76]
I have a mobile project using Expo, using this `@nrwl/expo` to generate it 

Inside `apps/my-project-folder/package.json`

```json
"devDependencies": {
    "@types/react": "~17.0.21"
  }
```

then in my root folder, I run `nx serve mobile`, I will get his prompt in terminal: 

> It looks like you're trying to use TypeScript but don't have the required

I choose like 18.0.1 in the choice. Then I get this: 

![image](https://user-images.githubusercontent.com/8010129/174086980-e859345a-8e8d-469b-816b-6b422f34ab7b.png)

After a while, I get this error: 

```
Require stack:
- D:\Desktop\MyProject\node_modules\expo-cli\build\exp.js
- D:\Desktop\MyProject\frontend\node_modules\expo-cli\bin\expo.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at _handleErrors (D:\Desktop\MyProjectt\frontend\node_modules\expo-cli\build\exp.js:232:16)
    at Command.<anonymous> (D:\Desktop\MyProject\frontend\node_modules\expo-cli\build\exp.js:563:17)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:19216) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
(node:19216) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**What I tried** 
I tried to go in `apps/my-project-folder/`
-  run `yarn`
- prompt this again: > It looks like you're trying to use TypeScript but don't have the required
- choose 1 of the version 
- successfully install the package 

Then
- go back to root folder 
- run `nx serve mobile` 

Right now I get this error: 
>  NX   ERROR  Could not find Nx modules in this workspace.

Looks like the `17.0.2` not exists, but I have no way to update it or modify it in the workspace folder 

Please point me to right direction

**Comment by kenchoong** [comment]
For context: 
I want to use Expo for mobile, Nextjs for web, not sure it is related or not 

 therefore here is my step to reproduce 

nx

> yarn create nx-workspace front --preset=empty

expo

> yarn add --dev @nrwl/expo

> nx generate @nrwl/expo:app mobile-app

nextjs

> yarn add --dev @nrwl/next

> nx g @nrwl/next:app web --e2eTestRunner=none

**Comment by webmandman** [comment]
nx version: 12.10.1
node: v16.13.2
npm: 8.1.2

When I run `npx nx g @nrwl/expo:app my-app` I get this:
```
npm ERR! notarget No matching version found for @types/react@18.1.0.
```

**Comment by xiongemi** [comment]
in your root's package.json, you might need to manually change the version: `"@types/react": "^17.0.45"`

**Comment by kenchoong** [comment]
yes @xiongemi, I can confirm that what u suggest is able to run expo. By the way, for next.js also able to start the app in localhost:4200 for now. 

But right now, in iOS, I unable to start the app in expo ios app. Will make another issue for that  

Thank you for you. This really helps. Close this for now.

**Comment by kenchoong** [comment]
Today I can confirm that after done what @xiongemi suggested, right now I successfully run web in Nextjs and both android and iOS in Expo Go.

**Comment by webmandman** [comment]
@xiongemi I updated @types/react to that verison you said and it almost worked. I got passed the other errors but now I get:
```
> nx run anotherapp:start
Packager is ready at http://localhost:8081
(node:33692) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
(Use `node --trace-deprecation ...` to show where the warning was created)
```

**Comment by xiongemi** [comment]
> @xiongemi I updated @types/react to that verison you said and it almost worked. I got passed the other errors but now I get:
> 
> ```
> > nx run anotherapp:start
> Packager is ready at http://localhost:8081
> (node:33692) [DEP0147] DeprecationWarning: In future versions of Node.js, fs.rmdir(path, { recursive: true }) will be removed. Use fs.rm(path, { recursive: true }) instead
> (Use `node --trace-deprecation ...` to show where the warning was created)
> ```

not sure where the error comes from, is it from the code or 3rd library? it seems like from node? what version of node and @types/node are you using? what is the verison of @nrwl/workspace are you using? maybe try to upgrade it by running `nx migrate latest`?
