### ISSUE TITLE
nx-ignore support for providing a custom base as an arg

### ISSUE THREAD

**Issue by burakkgunduzz** [nrwl/nx-labs#82]
### **The Problem and Current Behavior**
Hey, we are using nx-ignore in our monorepo hosted in vercel to determine which projects should build. However, since it considers the commit before head as a base commit, it does not always correctly decides which apps should build. For example, when the testing branch has several commits that touch different apps, and if these touches are individually in different commits (which is quite likely since we are merging PRs to testing branch that belong to different apps), the nx affected is trying to only check against HEAD^ and that behavior results with only re-build and deployment of the app that is affected in the commit one before HEAD when trying to merge testing into main.

### **Expected Behaviour**
We should be able to provide a custom base for the nx-ignore command for our different use cases to correctly ignore/determine unaffected projects. 

---
If you agree that this optional behavior would make sense, I can gladly make a contribution for it!

**Comment by jaysoo** [comment]
Merged, thanks!

**Comment by jaysoo** [comment]
Published 14.5.0

**Comment by burakkgunduzz** [comment]
For those who are experiencing the same problem with me, we created a .sh file under tools/vercel-deploy and give the path to vercel's ignore build step. The content of the file is like below.

```CURRENT_BRANCH=$(git branch --show-current)
LAST_MERGE_COMMIT_BEFORE_HEAD=$(git log --merges -n 2 --pretty=format:"%H" | tail -n 1)

if [ $CURRENT_BRANCH = testing ]; then
  npx nx-ignore your-app-name --base=$LAST_MERGE_COMMIT_BEFORE_HEAD
elif [ $CURRENT_BRANCH = main ]; then
  npx nx-ignore your-app-name --base=$LAST_MERGE_COMMIT_BEFORE_HEAD
else
  npx nx-ignore your-app-name
fi
```
In order for this code to work we always use merge commit. Basically this code checks if anything merged to testing or main, compare it against the previous merge (not previous commit), and if it is not merge (opened PR, push to PR), check against previous commit as  in the default case for nx-ignore which is important for vercel's preview deployments feature.

**Comment by theresasogunle** [comment]
Hi @burakkgunduzz thank you for your solution. I am trying to do this with three apps in my monorepo.What would be the best approach for this?

**Comment by juristr** [comment]
#109 might help

**Comment by burakkgunduzz** [comment]
I think you can create 3 different .sh file for each app in vercel-deploy folder and give each .sh path to relevant app's ignore-build step in vercel. @theresasogunle
