### ISSUE TITLE
Nx Expo -  "path" argument must be of type string. Received undefined

### ISSUE THREAD

**Issue by mikerudge** [nrwl/nx-labs#87]
I just tried adding a new expo app to an existing nx mono repo and I am getting the error

```
The "path" argument must be of type string. Received undefined
```

I decided to  try creating a new project and followed this blog
https://blog.nrwl.io/introducing-expo-support-for-nx-3fffb1849a6f

However, this gives me a similar error
```
TypeError: Cannot read property 'endsWith' of undefined\n" +
    '    at createProjectRootMappings (nx-expo-poetry/node_modules/nx/src/project-graph/file-map-utils.js:12:38)\n' +
``` 

Anyone got any ideas on where I can put the `path` so that it is not undefined?

Mac OS 12.3.1
NX version: 13.10.6

**Comment by leggomuhgreggo** [comment]
Also running into this

![image](https://user-images.githubusercontent.com/2213636/179338574-f552148c-9e40-4ac8-bc11-1ccafcb7bc61.png)

I thought it might be because of [this update](https://github.com/nrwl/nx-labs/commit/aa1392d5285c560cefab096721dccf9fa033057c#diff-d0ed6bc7ec2c8cb85f4c79c5f9b84f8ca898fe2f14fa4c7248e3a5a59b2194c3R10) but I made sure I had `project` and `watchFolders` defined correctly.

**Comment by xiongemi** [comment]
@leggomuhgreggo @mikerudge i added a migration script https://github.com/nrwl/nx-labs/commit/aa1392d5285c560cefab096721dccf9fa033057c#diff-25ec7d9495695fda92b26961d7285c1f2661842d49dd9217a152246dc9a3a564R13. 

if the migration script did not apply, you might manually update in your app's metro.config.js, in `return withNxMetro...`, add 
```
   projectRoot: __dirname,
    watchFolders: [],
```

so it becomes:
```
return withNxMetro(defaultConfig, {
    // Change this to true to see debugging info.
    // Useful if you have issues resolving modules
    debug: false,
    // all the file extensions used for imports other than 'ts', 'tsx', 'js', 'jsx'
    extensions: [],
    projectRoot: __dirname,
    watchFolders: [],
  });
```

**Comment by xiongemi** [comment]
close this issue with above solution.
