### ISSUE TITLE
No migrations.json

### ISSUE THREAD

**Issue by makhataibar** [nrwl/nx-labs#95]
In the latest @nrwl/expo missing migration.json
<img width="381" alt="Screen Shot 2022-08-03 at 17 35 02" src="https://user-images.githubusercontent.com/27006656/182598370-968186c8-d82b-41ee-be4e-69f9e4ac2d2f.png">

**Comment by xiongemi** [comment]
i deleted my node_modules folder and run `yarn install` again. it is fine for me for the latest @nrwl/expo version.
<img width="337" alt="Screen Shot 2022-08-05 at 1 12 21 PM" src="https://user-images.githubusercontent.com/16211801/183127458-e57d4586-f49f-482e-949f-9d193213c74d.png">

what version of @nrwl/expo are you using? could you run `nx report` in your repo and paste the response here?

**Comment by xiongemi** [comment]
i submitted a pr to fix this: https://github.com/nrwl/nx-labs/pull/100
